name: Node.js CI
on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
    - run: yarn install
    - run: yarn compile
    - run: yarn test
